name: walletmetrics-server CI

on: pull_request

jobs:
  Server_Build_Test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16.14.2"
          cache: "yarn"

      - uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          echo //npm.pkg.github.com/:_authToken=$NPM_TOKEN >> .npmrc
          yarn install --frozen-lockfile
          rm .npmrc

      - name: Test
        run: yarn test

      - name: Build
        run: yarn build
